import { ContextProviders } from "../components/ContextProviders";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Layout UI */}
        <main>
          <ContextProviders>
            {children}
          </ContextProviders>
        </main>
      </body>
    </html>
  )
}