import { ContextProviders } from "../components/ContextProviders";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ContextProviders>{children}</ContextProviders>
      </body>
    </html>
  );
}
